-- Base schema for the HerdMarket database (herdmarket_db).
-- Generated by introspecting the live development database with
-- `SHOW CREATE TABLE`, since no schema file previously existed in this repo.
--
-- This snapshot already reflects the database AFTER migrations 0001-0006
-- were applied (their columns are included below). For a FRESH database,
-- run ONLY this file — do not also run 0001-0006, they will fail with
-- "Duplicate column" errors since those columns already exist here.
-- Files 0001-0006 remain only as a historical changelog of how the schema
-- evolved. There is no migration runner in this repo — apply this file
-- manually, e.g. `mysql -u root -p herdmarket_db < migrations/0000_initial_schema.sql`.

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `full_name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(30) NOT NULL,
  `location` varchar(150) NOT NULL,
  `farm_location` varchar(150) DEFAULT NULL,
  `role` enum('farmer','buyer','admin') NOT NULL,
  `password` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `about` text DEFAULT NULL,
  `profile_image` varchar(255) DEFAULT NULL,
  `is_verified` tinyint(1) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `farm_lat` decimal(10,7) DEFAULT NULL,
  `farm_lng` decimal(10,7) DEFAULT NULL,
  `verification_document` text DEFAULT NULL,
  `verification_status` enum('Not Submitted','Pending','Approved','Rejected') NOT NULL DEFAULT 'Not Submitted',
  `verification_note` text DEFAULT NULL,
  `verification_submitted_at` timestamp NULL DEFAULT NULL,
  `reset_token_hash` char(64) DEFAULT NULL,
  `reset_token_expires` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `livestock_listings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `farmer_id` int(11) NOT NULL,
  `livestock_type` varchar(50) NOT NULL,
  `breed` varchar(100) DEFAULT NULL,
  `price` decimal(10,2) NOT NULL,
  `status` enum('Available','Pending','Sold','Flagged','Rejected','Removed') NOT NULL DEFAULT 'Available',
  `views` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `age` varchar(50) DEFAULT NULL,
  `weight` varchar(50) DEFAULT NULL,
  `health_status` varchar(100) DEFAULT NULL,
  `location` varchar(150) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `image_url` text DEFAULT NULL,
  `documents` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `farmer_id` (`farmer_id`),
  CONSTRAINT `livestock_listings_ibfk_1` FOREIGN KEY (`farmer_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `favorites` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `buyer_id` int(11) NOT NULL,
  `listing_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_favorite` (`buyer_id`,`listing_id`),
  KEY `listing_id` (`listing_id`),
  CONSTRAINT `favorites_ibfk_1` FOREIGN KEY (`buyer_id`) REFERENCES `users` (`id`),
  CONSTRAINT `favorites_ibfk_2` FOREIGN KEY (`listing_id`) REFERENCES `livestock_listings` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `inquiries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `listing_id` int(11) NOT NULL,
  `buyer_id` int(11) NOT NULL,
  `message` text DEFAULT NULL,
  `status` enum('Unread','Read','Negotiation','Completed') DEFAULT 'Unread',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `listing_id` (`listing_id`),
  KEY `buyer_id` (`buyer_id`),
  CONSTRAINT `inquiries_ibfk_1` FOREIGN KEY (`listing_id`) REFERENCES `livestock_listings` (`id`),
  CONSTRAINT `inquiries_ibfk_2` FOREIGN KEY (`buyer_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `conversations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `listing_id` int(11) NOT NULL,
  `farmer_id` int(11) NOT NULL,
  `buyer_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `farmer_last_read_at` datetime DEFAULT NULL,
  `buyer_last_read_at` datetime DEFAULT NULL,
  `farmer_deleted_at` datetime DEFAULT NULL,
  `buyer_deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `listing_id` (`listing_id`),
  KEY `farmer_id` (`farmer_id`),
  KEY `buyer_id` (`buyer_id`),
  CONSTRAINT `conversations_ibfk_1` FOREIGN KEY (`listing_id`) REFERENCES `livestock_listings` (`id`),
  CONSTRAINT `conversations_ibfk_2` FOREIGN KEY (`farmer_id`) REFERENCES `users` (`id`),
  CONSTRAINT `conversations_ibfk_3` FOREIGN KEY (`buyer_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `conversation_id` int(11) NOT NULL,
  `sender_id` int(11) NOT NULL,
  `message` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `listing_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `conversation_id` (`conversation_id`),
  KEY `sender_id` (`sender_id`),
  KEY `messages_listing_fk` (`listing_id`),
  CONSTRAINT `messages_ibfk_1` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`),
  CONSTRAINT `messages_ibfk_2` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`),
  CONSTRAINT `messages_listing_fk` FOREIGN KEY (`listing_id`) REFERENCES `livestock_listings` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `listing_id` int(11) NOT NULL,
  `farmer_id` int(11) NOT NULL,
  `buyer_id` int(11) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `workflow_step` enum('Inquiry','Negotiation','Verification','Confirmation','Completed') DEFAULT 'Inquiry',
  `status` enum('Pending','Completed','Flagged','Declined','Cancelled') DEFAULT 'Pending',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `listing_id` (`listing_id`),
  KEY `farmer_id` (`farmer_id`),
  KEY `buyer_id` (`buyer_id`),
  CONSTRAINT `transactions_ibfk_1` FOREIGN KEY (`listing_id`) REFERENCES `livestock_listings` (`id`),
  CONSTRAINT `transactions_ibfk_2` FOREIGN KEY (`farmer_id`) REFERENCES `users` (`id`),
  CONSTRAINT `transactions_ibfk_3` FOREIGN KEY (`buyer_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `notifications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(50) NOT NULL,
  `title` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `related_id` int(11) DEFAULT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `system_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `system_name` varchar(150) DEFAULT 'Web-Based Livestock Marketplace System',
  `municipality` varchar(150) DEFAULT 'Veruela, Agusan del Sur',
  `admin_office` varchar(150) DEFAULT 'Municipal Agriculture Office',
  `livestock_types` varchar(255) DEFAULT 'Swine, Cattle, Goat, Poultry',
  `default_listing_status` varchar(50) DEFAULT 'Pending Approval',
  `transaction_workflow` varchar(50) DEFAULT 'Strict Workflow',
  `secure_login` tinyint(4) DEFAULT 1,
  `role_based_access` tinyint(4) DEFAULT 1,
  `account_deactivation` tinyint(4) DEFAULT 1,
  `document_verification` tinyint(4) DEFAULT 1,
  `admin_notifications` tinyint(4) DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
